export enum Action {
  SHOW = "SHOW",
  HIDE = "HIDE",
  SEARCH = "SEARCH",
  MOVE_UP = "MOVE_UP",
  MOVE_DOWN = "MOVE_DOWN",
  UPDATE_LISTINGS = "UPDATE_LISTINGS",
  OPEN_LISTING = "OPEN_LISTING",
  OPEN_SELECTED_LISTING = "OPEN_SELECTED_LISTING",
}
